# Generated by Django 5.1.7 on 2025-04-06 19:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mentorados", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="mentorados",
            name="token",
            field=models.CharField(default=1, max_length=16),
            preserve_default=False,
        ),
    ]
